### ISSUE TITLE
Issue with regex-checker tools section

### ISSUE THREAD

**Issue by leelasaiprasanth** [YourAverageTechBro/DevToolboxWeb#12]
Hello 👋,

Recently i have gone through the tools, i could see them very helpful. Thanks for making it open source.

I could see there is some issue with the **regex-checker tool**, were initial loading of the tool doesnt output anything, while we update the email, the out was as expected, please go through the snippet's for reference, do let know if this is the default behavioral state of the tool ?
![image](https://github.com/YourAverageTechBro/DevToolboxWeb/assets/59244101/f1fe17d7-772a-483f-8e70-54b54001dddf)
![image](https://github.com/YourAverageTechBro/DevToolboxWeb/assets/59244101/5fe0b550-7539-4610-a415-a1a923588d38)

**Comment by YourAverageTechBro** [comment]
Definitely seems to be a bug. Please feel free make a PR with a fix if you would like. Personally a little busy with a few other things on my end so I won't be able to fix it for a few weeks.

**Comment by lucolvin** [comment]
Created pull request #17  with a possible fix
