### ISSUE TITLE
Line sort dedupe comma support

### ISSUE THREAD

**Issue by lucolvin** [YourAverageTechBro/DevToolboxWeb#36]
Currently if you add a list that is comma seperated it does nothing need to update with comma support.

i.e. 

Olivia, 
Ethan, 
Sophia, 
Liam, 
Ava, 
Jackson, Isabella, Lucas, Mia, Aiden, Harper, Elijah, Amelia, Logan, Abigail, Oliver, Charlotte, Noah, Emma, William, Grace, Luke

if organized in list on top of one-another it sorts but if side by side it fails and uses only the first word.

**Comment by shoeb00** [comment]
Hey, can I pick up this issue? Also, I think we can add two more things

1. Inline Data String Support

| Input            | Output |
| ---------------- | ------ |
| Beta Alpha Gamma | Alpha  |
|                  | Beta   |
|                  | Gamma  |

2. Remove Quotations

| Input                 | Output |
| --------------------- | ------ |
| "Beta", "Alpha", "Gamma" | Alpha  |
|                        | Beta   |
|                        | Gamma  |

**Comment by shoeb00** [comment]
Hey, I have created a [PR](https://github.com/YourAverageTechBro/DevToolboxWeb/pull/63) for this issue and its deployed on [vercel](https://dev-toolbox-web-mu.vercel.app/tools/line-sort-and-dedupe).
