### ISSUE TITLE
QRCode generator has no validation for length of input

### ISSUE THREAD

**Issue by tvt-joni** [YourAverageTechBro/DevToolboxWeb#54]
Minor issue but probably with a quick fix. If you enter too many characters or paste a very long text, it will crash.

**Comment by sabeerbikba** [comment]
### yes it's crashing if enter more then 2953
#### i thing good length is 1500 characters 

![crash](https://github.com/YourAverageTechBro/DevToolboxWeb/assets/59386700/a9ac34ba-d304-4c0f-a278-a400ae87ad6a)


![error](https://github.com/YourAverageTechBro/DevToolboxWeb/assets/59386700/4ef1d8cd-4702-41dc-93c2-3ffd84c25a25)
